# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: availability.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'availability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61vailability.proto\x12#services.vehiclestates.availability\"!\n\x12GetAvailabilityReq\x12\x0b\n\x03vin\x18\x02 \x01(\t\"<\n\x14\x41vailabilityDataHead\x12\x12\n\nupdateTime\x18\x01 \x01(\x03\x12\x10\n\x08unknown1\x18\x02 \x01(\x03\"\x82\x02\n\x10\x41vailabilityData\x12G\n\x04head\x18\x01 \x01(\x0b\x32\x39.services.vehiclestates.availability.AvailabilityDataHead\x12Q\n\x12\x65ngineLocalRunning\x18\x03 \x01(\x0e\x32\x35.services.vehiclestates.availability.AvailabilityBool\x12R\n\x12\x65ngineRunningState\x18\x05 \x01(\x0e\x32\x36.services.vehiclestates.availability.AvailabilityState\"g\n\x13GetAvailabilityResp\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x43\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x35.services.vehiclestates.availability.AvailabilityData*u\n\x11\x41vailabilityState\x12\x0b\n\x07Unknow1\x10\x00\x12\x0e\n\nNotRunning\x10\x01\x12\x10\n\x0cRuningRecent\x10\x02\x12\x0b\n\x07Unknow2\x10\x03\x12\x0b\n\x07Unknow3\x10\x04\x12\x17\n\x13RunningWithKeyInCar\x10\x05*0\n\x10\x41vailabilityBool\x12\x0b\n\x07Unknow4\x10\x00\x12\x06\n\x02No\x10\x01\x12\x07\n\x03Yes\x10\x02\x32\xa0\x01\n\x13\x41vailabilityService\x12\x88\x01\n\x0fGetAvailability\x12\x37.services.vehiclestates.availability.GetAvailabilityReq\x1a\x38.services.vehiclestates.availability.GetAvailabilityResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'availability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVAILABILITYSTATE']._serialized_start=522
  _globals['_AVAILABILITYSTATE']._serialized_end=639
  _globals['_AVAILABILITYBOOL']._serialized_start=641
  _globals['_AVAILABILITYBOOL']._serialized_end=689
  _globals['_GETAVAILABILITYREQ']._serialized_start=59
  _globals['_GETAVAILABILITYREQ']._serialized_end=92
  _globals['_AVAILABILITYDATAHEAD']._serialized_start=94
  _globals['_AVAILABILITYDATAHEAD']._serialized_end=154
  _globals['_AVAILABILITYDATA']._serialized_start=157
  _globals['_AVAILABILITYDATA']._serialized_end=415
  _globals['_GETAVAILABILITYRESP']._serialized_start=417
  _globals['_GETAVAILABILITYRESP']._serialized_end=520
  _globals['_AVAILABILITYSERVICE']._serialized_start=692
  _globals['_AVAILABILITYSERVICE']._serialized_end=852
# @@protoc_insertion_point(module_scope)
