# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: availability.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'availability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61vailability.proto\x12#services.vehiclestates.availability\"!\n\x12GetAvailabilityReq\x12\x0b\n\x03vin\x18\x02 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x03\"\xfc\x01\n\x10\x41vailabilityData\x12\x42\n\nupdatetime\x18\x01 \x01(\x0b\x32..services.vehiclestates.availability.Timestamp\x12P\n\x0f\x61vailableStatus\x18\x03 \x01(\x0e\x32\x37.services.vehiclestates.availability.AvailabilityStatus\x12R\n\x11unavailableReason\x18\x04 \x01(\x0e\x32\x37.services.vehiclestates.availability.AvailabilityReason\"g\n\x13GetAvailabilityResp\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12\x43\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x35.services.vehiclestates.availability.AvailabilityData*\x9f\x01\n\x12\x41vailabilityReason\x12\x10\n\x0cUnspecified1\x10\x00\x12\x0e\n\nNoInternet\x10\x01\x12\x13\n\x0fPowerSavingMode\x10\x02\x12\x0c\n\x08\x43\x61rInUse\x10\x03\x12\x1d\n\x19OtaInstallationInProgress\x10\x04\x12\x0b\n\x07Unknow1\x10\x05\x12\x0b\n\x07Unknow2\x10\x06\x12\x0b\n\x07Unknow3\x10\x07*F\n\x12\x41vailabilityStatus\x12\x10\n\x0cUnspecified2\x10\x00\x12\r\n\tAvailable\x10\x01\x12\x0f\n\x0bUnavailable\x10\x02\x32\xa0\x01\n\x13\x41vailabilityService\x12\x88\x01\n\x0fGetAvailability\x12\x37.services.vehiclestates.availability.GetAvailabilityReq\x1a\x38.services.vehiclestates.availability.GetAvailabilityResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'availability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVAILABILITYREASON']._serialized_start=500
  _globals['_AVAILABILITYREASON']._serialized_end=659
  _globals['_AVAILABILITYSTATUS']._serialized_start=661
  _globals['_AVAILABILITYSTATUS']._serialized_end=731
  _globals['_GETAVAILABILITYREQ']._serialized_start=59
  _globals['_GETAVAILABILITYREQ']._serialized_end=92
  _globals['_TIMESTAMP']._serialized_start=94
  _globals['_TIMESTAMP']._serialized_end=137
  _globals['_AVAILABILITYDATA']._serialized_start=140
  _globals['_AVAILABILITYDATA']._serialized_end=392
  _globals['_GETAVAILABILITYRESP']._serialized_start=394
  _globals['_GETAVAILABILITYRESP']._serialized_end=497
  _globals['_AVAILABILITYSERVICE']._serialized_start=734
  _globals['_AVAILABILITYSERVICE']._serialized_end=894
# @@protoc_insertion_point(module_scope)
