# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import availability_pb2 as availability__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in availability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AvailabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailability = channel.unary_stream(
            '/services.vehiclestates.availability.AvailabilityService/GetAvailability',
            request_serializer=availability__pb2.GetAvailabilityReq.SerializeToString,
            response_deserializer=availability__pb2.GetAvailabilityResp.FromString,
            _registered_method=True)


class AvailabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvailabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAvailability': grpc.unary_stream_rpc_method_handler(
            servicer.GetAvailability,
            request_deserializer=availability__pb2.GetAvailabilityReq.FromString,
            response_serializer=availability__pb2.GetAvailabilityResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'services.vehiclestates.availability.AvailabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        'services.vehiclestates.availability.AvailabilityService', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class AvailabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailability(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/services.vehiclestates.availability.AvailabilityService/GetAvailability',
            availability__pb2.GetAvailabilityReq.SerializeToString,
            availability__pb2.GetAvailabilityResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
