# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: car_preferences.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'car_preferences.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63\x61r_preferences.proto\x12\x0f\x63\x61r_preferences\" \n\x11GetPreferencesReq\x12\x0b\n\x03vin\x18\x01 \x01(\t\"\x1e\n\nPreference\x12\x10\n\x08nickName\x18\x01 \x01(\t\"E\n\x12GetPreferencesResp\x12/\n\npreference\x18\x01 \x01(\x0b\x32\x1b.car_preferences.Preference\"T\n\x14UpdatePreferencesReq\x12\x0b\n\x03vin\x18\x01 \x01(\t\x12/\n\npreference\x18\x02 \x01(\x0b\x32\x1b.car_preferences.Preference\"\x17\n\x15UpdatePreferencesResp2\xd7\x01\n\x0e\x43\x61rPreferences\x12]\n\x0eGetPreferences\x12\".car_preferences.GetPreferencesReq\x1a#.car_preferences.GetPreferencesResp\"\x00\x30\x01\x12\x66\n\x11UpdatePreferences\x12%.car_preferences.UpdatePreferencesReq\x1a&.car_preferences.UpdatePreferencesResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'car_preferences_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPREFERENCESREQ']._serialized_start=42
  _globals['_GETPREFERENCESREQ']._serialized_end=74
  _globals['_PREFERENCE']._serialized_start=76
  _globals['_PREFERENCE']._serialized_end=106
  _globals['_GETPREFERENCESRESP']._serialized_start=108
  _globals['_GETPREFERENCESRESP']._serialized_end=177
  _globals['_UPDATEPREFERENCESREQ']._serialized_start=179
  _globals['_UPDATEPREFERENCESREQ']._serialized_end=263
  _globals['_UPDATEPREFERENCESRESP']._serialized_start=265
  _globals['_UPDATEPREFERENCESRESP']._serialized_end=288
  _globals['_CARPREFERENCES']._serialized_start=291
  _globals['_CARPREFERENCES']._serialized_end=506
# @@protoc_insertion_point(module_scope)
