# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import exterior_pb2 as exterior__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in exterior_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExteriorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExterior = channel.unary_stream(
            '/services.vehiclestates.exterior.ExteriorService/GetExterior',
            request_serializer=exterior__pb2.GetExteriorReq.SerializeToString,
            response_deserializer=exterior__pb2.GetExteriorResp.FromString,
            _registered_method=True)


class ExteriorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExterior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExteriorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetExterior': grpc.unary_stream_rpc_method_handler(
            servicer.GetExterior,
            request_deserializer=exterior__pb2.GetExteriorReq.FromString,
            response_serializer=exterior__pb2.GetExteriorResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'services.vehiclestates.exterior.ExteriorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.vehiclestates.exterior.ExteriorService', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class ExteriorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExterior(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/services.vehiclestates.exterior.ExteriorService/GetExterior',
            exterior__pb2.GetExteriorReq.SerializeToString,
            exterior__pb2.GetExteriorResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
