# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: odometer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'odometer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eodometer.proto\x12\x1fservices.vehiclestates.odometer\"\x1d\n\x0eGetOdometerReq\x12\x0b\n\x03vin\x18\x02 \x01(\t\"8\n\x10odometerDataHead\x12\x12\n\nupdateTime\x18\x01 \x01(\x03\x12\x10\n\x08unknown1\x18\x02 \x01(\x03\"\xb6\x01\n\x0codometerData\x12?\n\x04head\x18\x01 \x01(\x0b\x32\x31.services.vehiclestates.odometer.odometerDataHead\x12\x15\n\rtotalDistance\x18\x02 \x01(\x03\x12\x12\n\nTMDistance\x18\x03 \x01(\x02\x12\x12\n\nTADistance\x18\x04 \x01(\x02\x12\x12\n\nTMAvgSpeed\x18\x05 \x01(\x05\x12\x12\n\nTAAvgSpeed\x18\x06 \x01(\x05\"[\n\x0fGetOdometerResp\x12\x0b\n\x03vin\x18\x02 \x01(\t\x12;\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32-.services.vehiclestates.odometer.odometerData2\x87\x01\n\x0fOdometerService\x12t\n\x0bGetOdometer\x12/.services.vehiclestates.odometer.GetOdometerReq\x1a\x30.services.vehiclestates.odometer.GetOdometerResp\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odometer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETODOMETERREQ']._serialized_start=51
  _globals['_GETODOMETERREQ']._serialized_end=80
  _globals['_ODOMETERDATAHEAD']._serialized_start=82
  _globals['_ODOMETERDATAHEAD']._serialized_end=138
  _globals['_ODOMETERDATA']._serialized_start=141
  _globals['_ODOMETERDATA']._serialized_end=323
  _globals['_GETODOMETERRESP']._serialized_start=325
  _globals['_GETODOMETERRESP']._serialized_end=416
  _globals['_ODOMETERSERVICE']._serialized_start=419
  _globals['_ODOMETERSERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
